// Generated by dmacro from example/openapi_demo/models.dmacro
// Do not edit — edit the source file instead.

// @dmacro-origin: example/openapi_demo/models.dmacro:10
class Category {
  final int? id;
  final String name;
  const Category({this.id, required this.name});
  Category copyWith({Object? id = _dmUndefined, String? name}) => Category(id: identical(id, _dmUndefined) ? this.id : id as int?, name: name ?? this.name);
  @override
  bool operator ==(Object other) => identical(this, other) || other is Category && other.id == id && other.name == name;
  @override
  int get hashCode => Object.hashAll([id, name]);
  @override
  String toString() => 'Category(id: $id, name: $name)';
  factory Category.fromJson(Map<String, dynamic> json) => Category(id: json['id'] as int?, name: json['name'] as String);
  Map<String, dynamic> toJson() => {'id': id, 'name': name};
}

// @dmacro-origin: example/openapi_demo/models.dmacro:11
class Pet {
  final int id;
  final String name;
  final String? tag;
  final Category? category;
  const Pet({required this.id, required this.name, this.tag, this.category});
  Pet copyWith({int? id, String? name, Object? tag = _dmUndefined, Object? category = _dmUndefined}) => Pet(id: id ?? this.id, name: name ?? this.name, tag: identical(tag, _dmUndefined) ? this.tag : tag as String?, category: identical(category, _dmUndefined) ? this.category : category as Category?);
  @override
  bool operator ==(Object other) => identical(this, other) || other is Pet && other.id == id && other.name == name && other.tag == tag && other.category == category;
  @override
  int get hashCode => Object.hashAll([id, name, tag, category]);
  @override
  String toString() => 'Pet(id: $id, name: $name, tag: $tag, category: $category)';
  factory Pet.fromJson(Map<String, dynamic> json) => Pet(id: json['id'] as int, name: json['name'] as String, tag: json['tag'] as String?, category: json['category'] == null ? null : Category.fromJson(json['category'] as Map<String, dynamic>));
  Map<String, dynamic> toJson() => {'id': id, 'name': name, 'tag': tag, 'category': category?.toJson()};
}

const Object _dmUndefined = Object();