// Generated by dmacro from example/payment.sexp
// Do not edit — edit the source file instead.

// @dmacro-origin: example/payment.sexp:11
class Payment {
  final double amount;
  final String currency;
  final String? reference;
  const Payment({required this.amount, required this.currency, this.reference});
  Payment copyWith(
          {double? amount,
          String? currency,
          Object? reference = _dmUndefined}) =>
      Payment(
          amount: amount ?? this.amount,
          currency: currency ?? this.currency,
          reference: identical(reference, _dmUndefined)
              ? this.reference
              : reference as String?);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Payment &&
          other.amount == amount &&
          other.currency == currency &&
          other.reference == reference;
  @override
  int get hashCode => Object.hashAll([amount, currency, reference]);
  @override
  String toString() =>
      'Payment(amount: $amount, currency: $currency, reference: $reference)';
  factory Payment.fromJson(Map<String, dynamic> json) => Payment(
      amount: (json['amount'] as num).toDouble(),
      currency: json['currency'] as String,
      reference: json['reference'] as String?);
  Map<String, dynamic> toJson() =>
      {'amount': amount, 'currency': currency, 'reference': reference};
}

// @dmacro-origin: example/payment.sexp:16
class TransferRequest {
  final Payment payment;
  final String fromAccount;
  final String toAccount;
  const TransferRequest(
      {required this.payment,
      required this.fromAccount,
      required this.toAccount});
  TransferRequest copyWith(
          {Payment? payment, String? fromAccount, String? toAccount}) =>
      TransferRequest(
          payment: payment ?? this.payment,
          fromAccount: fromAccount ?? this.fromAccount,
          toAccount: toAccount ?? this.toAccount);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransferRequest &&
          other.payment == payment &&
          other.fromAccount == fromAccount &&
          other.toAccount == toAccount;
  @override
  int get hashCode => Object.hashAll([payment, fromAccount, toAccount]);
  @override
  String toString() =>
      'TransferRequest(payment: $payment, fromAccount: $fromAccount, toAccount: $toAccount)';
  factory TransferRequest.fromJson(Map<String, dynamic> json) =>
      TransferRequest(
          payment: Payment.fromJson(json['payment'] as Map<String, dynamic>),
          fromAccount: json['fromAccount'] as String,
          toAccount: json['toAccount'] as String);
  Map<String, dynamic> toJson() => {
        'payment': payment.toJson(),
        'fromAccount': fromAccount,
        'toAccount': toAccount
      };
}

// @dmacro-origin: example/payment.sexp:25
bool validatePayment(double amount, String currency) {
  if (!(amount > 0)) {
    throw Exception("Amount must be positive");
  }
  if (!(currency != "")) {
    throw Exception("Currency must not be empty");
  }
  if (!(amount <= 1000000)) {
    throw AssertionError("Expected: (amount <= 1000000), got false");
  }
  if (!(amount >= 0.01)) {
    throw AssertionError("Expected: (amount >= 0.01), got false");
  }
  return true;
}

// @dmacro-origin: example/payment.sexp:38
void postJson(String endpoint, Payment payment) {
  print("POST");
}

// @dmacro-origin: example/payment.sexp:41
void processPayment(Payment payment, String endpoint) {
  for (final dmAttempt_0 in Iterable.generate(3)) {
    try {
      postJson(endpoint, payment);
      break;
    } catch (dmErr_1) {
      if ((dmAttempt_0 == (3 - 1))) {
        rethrow;
      } else {
        print("Retrying...");
      }
    }
  }
}

// @dmacro-origin: example/payment.sexp:48
String describeBalance(double balance) {
  if (!(balance >= 0)) {
    return "overdrawn";
  }
  if ((balance > 10000)) {
    return "high balance";
  }
  return "normal";
}

// @dmacro-origin: example/payment.sexp:59
void sortPair(double a, double b) {
  if ((a > b)) {
    final dmSwap_2 = a;
    a = b;
    b = dmSwap_2;
  }
}

const Object _dmUndefined = Object();
