// Generated by dmacro from example/payment.dmacro
// Do not edit — edit the source file instead.

// @dmacro-origin: example/payment.dmacro:12
class Payment {
  // @dmacro-origin: example/payment.dmacro:13
  final double amount;
  // @dmacro-origin: example/payment.dmacro:14
  final String currency;
  // @dmacro-origin: example/payment.dmacro:15
  final String? reference;
  const Payment({required this.amount, required this.currency, this.reference});
  Payment copyWith(
          {double? amount,
          String? currency,
          Object? reference = _dmUndefined}) =>
      Payment(
          amount: amount ?? this.amount,
          currency: currency ?? this.currency,
          reference: identical(reference, _dmUndefined)
              ? this.reference
              : reference as String?);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Payment &&
          other.amount == amount &&
          other.currency == currency &&
          other.reference == reference;
  @override
  int get hashCode => Object.hashAll([amount, currency, reference]);
  @override
  String toString() =>
      'Payment(amount: $amount, currency: $currency, reference: $reference)';
  factory Payment.fromJson(Map<String, dynamic> json) => Payment(
      amount: (json['amount'] as num).toDouble(),
      currency: json['currency'] as String,
      reference: json['reference'] as String?);
  Map<String, dynamic> toJson() =>
      {'amount': amount, 'currency': currency, 'reference': reference};
}

// @dmacro-origin: example/payment.dmacro:18
class TransferRequest {
  // @dmacro-origin: example/payment.dmacro:19
  final Payment payment;
  // @dmacro-origin: example/payment.dmacro:20
  final String fromAccount;
  // @dmacro-origin: example/payment.dmacro:21
  final String toAccount;
  const TransferRequest(
      {required this.payment,
      required this.fromAccount,
      required this.toAccount});
  TransferRequest copyWith(
          {Payment? payment, String? fromAccount, String? toAccount}) =>
      TransferRequest(
          payment: payment ?? this.payment,
          fromAccount: fromAccount ?? this.fromAccount,
          toAccount: toAccount ?? this.toAccount);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransferRequest &&
          other.payment == payment &&
          other.fromAccount == fromAccount &&
          other.toAccount == toAccount;
  @override
  int get hashCode => Object.hashAll([payment, fromAccount, toAccount]);
  @override
  String toString() =>
      'TransferRequest(payment: $payment, fromAccount: $fromAccount, toAccount: $toAccount)';
  factory TransferRequest.fromJson(Map<String, dynamic> json) =>
      TransferRequest(
          payment: Payment.fromJson(json['payment'] as Map<String, dynamic>),
          fromAccount: json['fromAccount'] as String,
          toAccount: json['toAccount'] as String);
  Map<String, dynamic> toJson() => {
        'payment': payment.toJson(),
        'fromAccount': fromAccount,
        'toAccount': toAccount
      };
}

// @dmacro-origin: example/payment.dmacro:24
sealed class PaymentState {
  const PaymentState();
}

class Idle extends PaymentState {
  const Idle();
  Idle copyWith() => Idle();
  @override
  bool operator ==(Object other) => identical(this, other) || other is Idle;
  @override
  int get hashCode => Object.hashAll([]);
  @override
  String toString() => 'Idle()';
}

class Loading extends PaymentState {
  const Loading();
  Loading copyWith() => Loading();
  @override
  bool operator ==(Object other) => identical(this, other) || other is Loading;
  @override
  int get hashCode => Object.hashAll([]);
  @override
  String toString() => 'Loading()';
}

class Success extends PaymentState {
  final Payment payment;
  const Success({required this.payment});
  Success copyWith({Payment? payment}) =>
      Success(payment: payment ?? this.payment);
  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is Success && other.payment == payment;
  @override
  int get hashCode => Object.hashAll([payment]);
  @override
  String toString() => 'Success(payment: $payment)';
}

class Failure extends PaymentState {
  final String error;
  const Failure({required this.error});
  Failure copyWith({String? error}) => Failure(error: error ?? this.error);
  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is Failure && other.error == error;
  @override
  int get hashCode => Object.hashAll([error]);
  @override
  String toString() => 'Failure(error: $error)';
}

// @dmacro-origin: example/payment.dmacro:39
bool validatePayment(double amount, String currency) {
  if (!(amount > 0)) {
    throw Exception("Amount must be positive");
  }
  if (!(currency != "")) {
    throw Exception("Currency must not be empty");
  }
  if (!(amount <= 1000000)) {
    throw AssertionError("Expected: (amount <= 1000000), got false");
  }
  return true;
}

// @dmacro-origin: example/payment.dmacro:55
void sendToApi(String endpoint, Payment payment) {
  print("POST $endpoint amount=");
}

// @dmacro-origin: example/payment.dmacro:59
void processPayment(Payment payment, String endpoint) {
  for (final __attempt_0 in Iterable.generate(3)) {
    try {
      sendToApi(endpoint, payment);
      break;
    } catch (__err_1) {
      if ((__attempt_0 == (3 - 1))) {
        throw __err_1;
      } else {
        print("Retrying...");
      }
    }
  }
}

// @dmacro-origin: example/payment.dmacro:67
void normalise(double a, double b) {
  if ((a > b)) {
    final __swap_2 = a;
    a = b;
    b = __swap_2;
  }
}

// @dmacro-origin: example/payment.dmacro:75
String describeAmount(double amount) {
  if ((amount < 0)) {
    return "negative";
  }
  if ((amount > 10000)) {
    return "large";
  }
  return "normal";
}

const Object? _dmUndefined = Object();
