/// dart_sexp compiler CLI
///
/// Usage:
///   dart run bin/sexp.dart compile <file.sexp>   — compile to stdout
///   dart run bin/sexp.dart compile <file.sexp> -o <out.dart>
///   dart run bin/sexp.dart repl                  — interactive REPL
import 'dart:io';

import '../lib/src/builtins.dart';
import '../lib/src/reader.dart';

void main(List<String> args) async {
  registerBuiltins();

  if (args.isEmpty || args.first == 'help') {
    _printUsage();
    return;
  }

  switch (args.first) {
    case 'compile':
      await _compile(args.sublist(1));
    case 'repl':
      await _repl();
    default:
      stderr.writeln('Unknown command: ${args.first}');
      _printUsage();
      exit(1);
  }
}

// ─── Commands ────────────────────────────────────────────────────────────────

Future<void> _compile(List<String> args) async {
  if (args.isEmpty) {
    stderr.writeln('Usage: sexp compile <file.sexp> [-o output.dart]');
    exit(1);
  }

  final inputPath  = args[0];
  final outputPath = args.length >= 3 && args[1] == '-o' ? args[2] : null;

  final source = await File(inputPath).readAsString();

  try {
    final dart = compile(source);
    final header = '// Generated by dart_sexp from $inputPath\n'
                   '// Do not edit — edit the .sexp source instead.\n\n';
    final output = header + dart;

    if (outputPath != null) {
      await File(outputPath).writeAsString(output);
      print('✓ $inputPath → $outputPath');
    } else {
      print(output);
    }
  } on ReaderException catch (e) {
    stderr.writeln('Reader error: $e');
    exit(1);
  } catch (e) {
    stderr.writeln('Compile error: $e');
    exit(1);
  }
}

/// Interactive REPL — type S-expressions, see Dart output immediately.
Future<void> _repl() async {
  print('dart_sexp REPL  (Ctrl+C to exit)');
  print('Type S-expressions and see the compiled Dart output.\n');

  while (true) {
    stdout.write('sexp> ');
    final line = stdin.readLineSync();
    if (line == null) break;
    if (line.trim().isEmpty) continue;

    try {
      final dart = compile(line);
      print('→ $dart\n');
    } on ReaderException catch (e) {
      print('Error: $e\n');
    } catch (e) {
      print('Error: $e\n');
    }
  }
}

void _printUsage() {
  print('''
dart_sexp — Lisp-style macros that compile to Dart

Usage:
  dart run bin/sexp.dart compile <file.sexp>            Print Dart to stdout
  dart run bin/sexp.dart compile <file.sexp> -o out.dart  Write to file
  dart run bin/sexp.dart repl                           Interactive REPL

Syntax:
  (form arg arg ...)   — list / function call / macro call
  "string"             — string literal
  42  3.14             — numbers
  true  false  null    — literals
  symbol               — identifier, operator, or Dart type
  ; comment            — line comment

Built-in macros:
  (unless condition body)         Custom control flow
  (when condition body)           Custom control flow
  (swap! a b)                     Variable swap — injects temp var
  (with-retry n body)             Retry loop with state
  (assert-that expr)              Error message contains source expr
  (defrecord Name [T f] ...)      Generates entire immutable class
  (defunion Name [Variant ...])   Generates sealed class hierarchy
  (and-let [name expr] ... body)  Cascading bindings
''');
}
