// Generated by dmacro from example/use_macros/models.dmacro
// Do not edit — edit the source file instead.
// ignore_for_file: type=lint

// @dmacro-origin: example/use_macros/models.dmacro:2

// @dmacro-origin: example/use_macros/models.dmacro:5
class User {
  final String id;
  final String name;
  final int age;

  const User(this.id, this.name, this.age);
}

// @dmacro-origin: example/use_macros/models.dmacro:11
class Product {
  final String sku;
  final double price;

  const Product(this.sku, this.price);
}
