/// Parent side of `useMacros` — spawns and talks to macro worker isolates.
///
/// `useMacros("package:team/macros.dart")` loads a Dart macro library with **no
/// `tool/dmacro.dart` entry point**. Because closures cannot cross isolate
/// boundaries, the library runs in a worker isolate (see `macro_worker.dart`)
/// that owns its macros; here in the parent we register one thin proxy per
/// macro name. Each proxy forwards a single `(name, args) → Node` call to the
/// worker and returns the raw result, which the parent's expander continues to
/// expand — so worker macros compose with builtins, templates, and each other.
///
/// Workers persist for the whole compile run (one spawn per library, cached)
/// and are torn down by [shutdownMacroWorkers], which `runDmacro` calls when it
/// finishes.
library;

import 'dart:async';
import 'dart:io';
import 'dart:isolate';

import 'async_expand.dart';
import 'core.dart';
import 'node_codec.dart';

class _Worker {
  final Isolate isolate;
  final SendPort requests;
  final ReceivePort replies;
  final File bootstrap;
  final _pending = <int, Completer<Node>>{};
  var _nextId = 0;

  _Worker(this.isolate, this.requests, this.replies, this.bootstrap) {
    replies.listen((msg) {
      final m = msg as Map;
      final completer = _pending.remove(m['id']);
      if (completer == null) return;
      if (m.containsKey('err')) {
        completer.completeError(MacroExpansionError(m['err'] as String));
      } else {
        completer.complete(decodeNode(m['ok']));
      }
    });
  }

  Future<Node> call(String name, List<Node> args) {
    final id = _nextId++;
    final completer = Completer<Node>();
    _pending[id] = completer;
    requests.send({
      'id': id,
      'name': name,
      'args': encodeNode(args),
      'reply': replies.sendPort,
    });
    return completer.future;
  }

  void shutdown() {
    requests.send('shutdown');
    replies.close();
    isolate.kill(priority: Isolate.immediate);
    try {
      if (bootstrap.existsSync()) bootstrap.deleteSync();
    } on FileSystemException {
      // Best-effort cleanup; a leftover bootstrap under .dart_tool is harmless.
    }
  }
}

// Keyed by "uri#fn" so the same library is only ever loaded once per run.
final _workers = <String, _Worker>{};

/// Loads the Dart macro library at [target] in a worker isolate and registers
/// a proxy macro for every macro it exposes. [target] is a `package:` URI or a
/// path to a `.dart` file; an optional `#functionName` fragment names the
/// registration function (default `registerMacros`).
///
/// Idempotent: loading the same target twice in one run is a no-op.
Future<void> loadMacroLibrary(String target) async {
  final hashIndex = target.indexOf('#');
  final uriPart = hashIndex == -1 ? target : target.substring(0, hashIndex);
  final fnName =
      hashIndex == -1 ? 'registerMacros' : target.substring(hashIndex + 1);

  final cacheKey = '$uriPart#$fnName';
  if (_workers.containsKey(cacheKey)) return;

  final importUri = _toImportUri(uriPart);

  final bootDir = Directory('.dart_tool/dmacro');
  bootDir.createSync(recursive: true);
  final bootstrap = File(
      '${bootDir.path}/bootstrap_${cacheKey.hashCode.toUnsigned(32)}.dart');
  bootstrap.writeAsStringSync('''
// GENERATED by dmacro for a useMacros("$uriPart") directive. Safe to delete.
import 'dart:isolate';
import 'package:dmacro/src/macro_worker.dart';
import '$importUri' as lib;

void main(List<String> args, SendPort port) =>
    runMacroWorker(port, [lib.$fnName]);
''');

  final handshake = ReceivePort();
  final Isolate isolate;
  try {
    isolate = await Isolate.spawnUri(
      bootstrap.absolute.uri,
      const [],
      handshake.sendPort,
      packageConfig: _packageConfigUri(),
    );
  } on IsolateSpawnException catch (e) {
    handshake.close();
    if (bootstrap.existsSync()) bootstrap.deleteSync();
    throw MacroExpansionError(
      'useMacros: failed to load "$uriPart".\n'
      '  The target must be a Dart file exposing `void $fnName()` that '
      'registers macros, and `dart pub get` must have been run.\n'
      '  Cause: ${e.message}',
    );
  }

  final hs = await handshake.first as Map;
  handshake.close();
  final worker = _Worker(
    isolate,
    hs['port'] as SendPort,
    ReceivePort(),
    bootstrap,
  );
  _workers[cacheKey] = worker;

  for (final name in (hs['names'] as List).cast<String>()) {
    defAsyncMacro(name, (args) => worker.call(name, args));
  }
}

/// Shuts down every worker isolate spawned this run and deletes their generated
/// bootstraps. Called by `runDmacro` after compilation; safe to call when no
/// workers exist.
void shutdownMacroWorkers() {
  for (final worker in _workers.values) {
    worker.shutdown();
  }
  _workers.clear();
}

/// Converts a `useMacros` target into something importable from the generated
/// bootstrap: `package:` URIs pass through; anything else is treated as a
/// filesystem path and resolved to an absolute `file:` URI.
String _toImportUri(String target) {
  if (target.startsWith('package:') ||
      target.startsWith('dart:') ||
      target.startsWith('file:')) {
    return target;
  }
  return File(target).absolute.uri.toString();
}

/// Locates the project's package_config.json so the worker resolves the same
/// `package:` dependencies as the running compile. Returns null to let
/// [Isolate.spawnUri] inherit the parent's configuration.
Uri? _packageConfigUri() {
  var dir = Directory.current;
  for (var i = 0; i < 10; i++) {
    final cfg = File('${dir.path}/.dart_tool/package_config.json');
    if (cfg.existsSync()) return cfg.absolute.uri;
    final parent = dir.parent;
    if (parent.path == dir.path) break;
    dir = parent;
  }
  return null;
}
