// Generated by dmacro from example/macro_library/app.dmacro
// Do not edit — edit the source file instead.

// @dmacro-origin: example/macro_library/app.dmacro:6


// @dmacro-origin: example/macro_library/app.dmacro:9
class SubmitButton extends StatelessWidget {
  final String label;
  final VoidCallback onPressed;
  final bool? disabled;

  const SubmitButton({super.key, required this.label, required this.onPressed, this.disabled});

  @override
  Widget build(BuildContext context) {
    throw UnimplementedError('implement $name.build');
  }
}

// @dmacro-origin: example/macro_library/app.dmacro:16
void processOrder(String id, int qty) {
  if (!(id != "")) {
    throw ArgumentError("requirement failed");
  }
  if (!(qty > 0)) {
    throw ArgumentError("requirement failed");
  }
  if (!(qty < 1000)) {
    throw ArgumentError("requirement failed");
  }
  print(id);
  print(qty);
}

// @dmacro-origin: example/macro_library/app.dmacro:22
String validateEmail(String email) {
  if ((email == "")) {
    throw ArgumentError("email must not be empty");
  }
  return email;
}