// Generated by dmacro from example/macro_library/app.dmacro
// Do not edit — edit the source file instead.
// ignore_for_file: type=lint

// @dmacro-origin: example/macro_library/app.dmacro:10

// @dmacro-origin: example/macro_library/app.dmacro:12
void processOrder(String id, int qty) {
  if (!(id != "")) {
    throw ArgumentError("requirement failed");
  }
  if (!(qty > 0)) {
    throw ArgumentError("requirement failed");
  }
  if (!(qty < 1000)) {
    throw ArgumentError("requirement failed");
  }
  print(id);
  print(qty);
}

// @dmacro-origin: example/macro_library/app.dmacro:17
String validate(String value, String field) {
  if (!(value != "")) {
    throw ArgumentError("requirement failed");
  }
  return value;
}
