// Generated by dmacro from example/showcase/app.dmacro
// Do not edit — edit the source file instead.
// ignore_for_file: type=lint

// @dmacro-origin: example/showcase/app.dmacro:9

// @dmacro-origin: example/showcase/app.dmacro:11

// @dmacro-origin: example/showcase/app.dmacro:15
enum Role {
  admin,
  editor,
  viewer;

  factory Role.fromJson(String s) => Role.values.byName(s);
  String toJson() => name;
}

// @dmacro-origin: example/showcase/app.dmacro:20
class Account {
  final String id;
  final Role role;
  final DateTime createdAt;
  const Account(
      {required this.id, required this.role, required this.createdAt});
  Account copyWith({String? id, Role? role, DateTime? createdAt}) => Account(
      id: id ?? this.id,
      role: role ?? this.role,
      createdAt: createdAt ?? this.createdAt);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Account &&
          other.id == id &&
          other.role == role &&
          other.createdAt == createdAt;
  @override
  int get hashCode => Object.hashAll([id, role, createdAt]);
  @override
  String toString() => 'Account(id: $id, role: $role, createdAt: $createdAt)';
  factory Account.fromJson(Map<String, dynamic> json) => Account(
      id: json['id'] as String,
      role: Role.values.byName(json['role'] as String),
      createdAt: DateTime.parse(json['createdAt'] as String));
  Map<String, dynamic> toJson() =>
      {'id': id, 'role': role.name, 'createdAt': createdAt.toIso8601String()};
}

// @dmacro-origin: example/showcase/app.dmacro:27
sealed class AuthState {
  const AuthState();
}

class SignedOut extends AuthState {
  const SignedOut();
  SignedOut copyWith() => SignedOut();
  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is SignedOut;
  @override
  int get hashCode => Object.hashAll([]);
  @override
  String toString() => 'SignedOut()';
}

class Authenticating extends AuthState {
  const Authenticating();
  Authenticating copyWith() => Authenticating();
  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is Authenticating;
  @override
  int get hashCode => Object.hashAll([]);
  @override
  String toString() => 'Authenticating()';
}

class SignedIn extends AuthState {
  final Account account;
  const SignedIn({required this.account});
  SignedIn copyWith({Account? account}) =>
      SignedIn(account: account ?? this.account);
  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is SignedIn && other.account == account;
  @override
  int get hashCode => Object.hashAll([account]);
  @override
  String toString() => 'SignedIn(account: $account)';
}

class Failed extends AuthState {
  final String error;
  const Failed({required this.error});
  Failed copyWith({String? error}) => Failed(error: error ?? this.error);
  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is Failed && other.error == error;
  @override
  int get hashCode => Object.hashAll([error]);
  @override
  String toString() => 'Failed(error: $error)';
}

// @dmacro-origin: example/showcase/app.dmacro:37
class User {
  final String id;
  final String email;
  final String fullName;
  final DateTime createdAt;
  final List<String>? tags;
  const User(
      {required this.id,
      required this.email,
      required this.fullName,
      required this.createdAt,
      this.tags});
  User copyWith(
          {String? id,
          String? email,
          String? fullName,
          DateTime? createdAt,
          Object? tags = _dmUndefined}) =>
      User(
          id: id ?? this.id,
          email: email ?? this.email,
          fullName: fullName ?? this.fullName,
          createdAt: createdAt ?? this.createdAt,
          tags: identical(tags, _dmUndefined)
              ? this.tags
              : tags as List<String>?);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is User &&
          other.id == id &&
          other.email == email &&
          other.fullName == fullName &&
          other.createdAt == createdAt &&
          _dmEq(other.tags, tags);
  @override
  int get hashCode =>
      Object.hashAll([id, email, fullName, createdAt, _dmHash(tags)]);
  @override
  String toString() =>
      'User(id: $id, email: $email, fullName: $fullName, createdAt: $createdAt, tags: $tags)';
  factory User.fromJson(Map<String, dynamic> json) => User(
      id: json['id'] as String,
      email: json['email'] as String,
      fullName: json['fullName'] as String,
      createdAt: DateTime.parse(json['createdAt'] as String),
      tags: json['tags'] == null
          ? null
          : (json['tags'] as List).map((e) => e as String).toList());
  Map<String, dynamic> toJson() => {
        'id': id,
        'email': email,
        'fullName': fullName,
        'createdAt': createdAt.toIso8601String(),
        'tags': tags
      };
}

// @dmacro-origin: example/showcase/app.dmacro:41
class CreateUserRequest {
  final String email;
  final String fullName;
  final bool? sendWelcome;

  const CreateUserRequest(
      {required this.email, required this.fullName, this.sendWelcome});
}

// @dmacro-origin: example/showcase/app.dmacro:50
bool validateSignup(String email, String name, int age) {
  if (!email.isNotEmpty) {
    throw ArgumentError("email required");
  }
  if (!name.isNotEmpty) {
    throw ArgumentError("name required");
  }
  if (!(email != "")) {
    throw ArgumentError("requirement failed");
  }
  if (!(age >= 13)) {
    throw ArgumentError("requirement failed");
  }
  if (!(age < 120)) {
    throw ArgumentError("requirement failed");
  }
  if (!((age >= 0) && (age <= 150))) {
    throw RangeError("value out of range");
  }
  if (!email.contains("@")) {
    throw FormatException("invalid email");
  }
  if (!(name.length < 100)) {
    throw AssertionError("Expected: (name.length < 100), got false");
  }
  return true;
}

// @dmacro-origin: example/showcase/app.dmacro:65
void deliver(String endpoint, Account account) {
  print("POST $endpoint for ${account.id}");
}

// @dmacro-origin: example/showcase/app.dmacro:69
void sendWithRetry(String endpoint, Account account) {
  for (final dmAttempt_0 in Iterable.generate(3)) {
    try {
      deliver(endpoint, account);
      break;
    } catch (dmErr_1) {
      if ((dmAttempt_0 == (3 - 1))) {
        rethrow;
      } else {
        print("Retrying...");
      }
    }
  }
}

// @dmacro-origin: example/showcase/app.dmacro:73
void normaliseBounds(int lo, int hi) {
  if ((lo > hi)) {
    final dmSwap_2 = lo;
    lo = hi;
    hi = dmSwap_2;
  }
}

// @dmacro-origin: example/showcase/app.dmacro:80
String roleLabel(Role role) {
  if ((role == Role.admin)) {
    return "Administrator";
  }
  if ((role == Role.editor)) {
    return "Editor";
  }
  return "Viewer";
}

const Object _dmUndefined = Object();

/// Structural equality for List/Set/Map fields (generated by dmacro).
bool _dmEq(Object? a, Object? b) {
  if (identical(a, b)) return true;
  if (a is List && b is List) {
    if (a.length != b.length) return false;
    for (var i = 0; i < a.length; i++) {
      if (!_dmEq(a[i], b[i])) return false;
    }
    return true;
  }
  if (a is Set && b is Set) {
    if (a.length != b.length) return false;
    for (final e in a) {
      if (!b.any((o) => _dmEq(e, o))) return false;
    }
    return true;
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) return false;
    for (final k in a.keys) {
      if (!b.containsKey(k) || !_dmEq(a[k], b[k])) return false;
    }
    return true;
  }
  return a == b;
}

/// Structural hash for List/Set/Map fields (generated by dmacro).
int _dmHash(Object? v) {
  if (v is List) return Object.hashAll(v.map(_dmHash));
  if (v is Set) return Object.hashAllUnordered(v.map(_dmHash));
  if (v is Map) {
    return Object.hashAllUnordered(
        v.entries.map((e) => Object.hash(_dmHash(e.key), _dmHash(e.value))));
  }
  return v.hashCode;
}
