// Generated by dmacro from example/schema_demo/models.dmacro
// Do not edit — edit the source file instead.

// @dmacro-origin: example/schema_demo/models.dmacro:1
class Payment {
  final double amount;
  final String currency;
  final String? reference;
  final List<String>? tags;
  const Payment(
      {required this.amount,
      required this.currency,
      this.reference,
      this.tags});
  Payment copyWith(
          {double? amount,
          String? currency,
          Object? reference = _dmUndefined,
          Object? tags = _dmUndefined}) =>
      Payment(
          amount: amount ?? this.amount,
          currency: currency ?? this.currency,
          reference: identical(reference, _dmUndefined)
              ? this.reference
              : reference as String?,
          tags: identical(tags, _dmUndefined)
              ? this.tags
              : tags as List<String>?);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Payment &&
          other.amount == amount &&
          other.currency == currency &&
          other.reference == reference &&
          _dmEq(other.tags, tags);
  @override
  int get hashCode =>
      Object.hashAll([amount, currency, reference, _dmHash(tags)]);
  @override
  String toString() =>
      'Payment(amount: $amount, currency: $currency, reference: $reference, tags: $tags)';
  factory Payment.fromJson(Map<String, dynamic> json) => Payment(
      amount: (json['amount'] as num).toDouble(),
      currency: json['currency'] as String,
      reference: json['reference'] as String?,
      tags: json['tags'] == null
          ? null
          : (json['tags'] as List).map((e) => e as String).toList());
  Map<String, dynamic> toJson() => {
        'amount': amount,
        'currency': currency,
        'reference': reference,
        'tags': tags
      };
}

const Object? _dmUndefined = Object();

/// Structural equality for List/Set/Map fields (generated by dmacro).
bool _dmEq(Object? a, Object? b) {
  if (identical(a, b)) return true;
  if (a is List && b is List) {
    if (a.length != b.length) return false;
    for (var i = 0; i < a.length; i++) {
      if (!_dmEq(a[i], b[i])) return false;
    }
    return true;
  }
  if (a is Set && b is Set) {
    if (a.length != b.length) return false;
    for (final e in a) {
      if (!b.any((o) => _dmEq(e, o))) return false;
    }
    return true;
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) return false;
    for (final k in a.keys) {
      if (!b.containsKey(k) || !_dmEq(a[k], b[k])) return false;
    }
    return true;
  }
  return a == b;
}

/// Structural hash for List/Set/Map fields (generated by dmacro).
int _dmHash(Object? v) {
  if (v is List) return Object.hashAll(v.map(_dmHash));
  if (v is Set) return Object.hashAllUnordered(v.map(_dmHash));
  if (v is Map) {
    return Object.hashAllUnordered(
        v.entries.map((e) => Object.hash(_dmHash(e.key), _dmHash(e.value))));
  }
  return v.hashCode;
}
